### ISSUE TITLE
Allow download and export of items to read-only rights.

### ISSUE THREAD

**Issue by swouf** [graasp/graasp-builder#442] opened 2022-09-15 10:14 UTC
Some users asked how to download the material from a Graasp folder to which they had only read access. It was possible to do it file by file by viewing and downloading them through the browser. We could (should?) allow that in the platform directly.

The following line should be modified to display the download button even when users have only read access:
https://github.com/graasp/graasp-compose/blob/1f6f5089f2ffc6674e8f49281b898ab95165ee2a/src/components/table/ActionsCellRenderer.js#L41

**Comment by pyphilia** [comment] 2023-09-11 08:57
@swouf duplicate of #748 ?

**Comment by swouf** [comment] 2023-09-11 09:03
> @swouf duplicate of #748 ?

Yes, it is the exact same issue.

**Closed** 2024-08-07 12:18 UTC
Labels: feature
